default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: uma_note_development
  username: postgres
  password: password

test:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: uma_note_test
  username: postgres
  password: password

production:
  url: <%= ENV['DATABASE_URL'] %>