default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: db
  database: uma_note_development
  username: postgres
  password: password

test:
  <<: *default
  host: db
  database: uma_note_test
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'].presence || "postgresql://dummy:dummy@localhost:5432/dummy" %>